language: objective-c
osx_image: xcode10.1
xcode_project: ModelSynchro.xcodeproj
xcode_scheme: ModelSynchro
xcode_destination: platform=macOS
before_install:
- cd ModelSynchroLibrary
- swift package update
- swift package generate-xcodeproj
script:
  - set -o pipefail && xcodebuild -project ModelSynchroLibrary.xcodeproj -scheme ModelSynchroLibrary-Package -destination platform\=macOS build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty